name: Create and Release Tag

on:
  workflow_dispatch:
    inputs:
      release-tag-number:
        description: 'Enter the release-tag number'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Release Tag
        uses: ./
        with:
          release-tag-number: ${{ github.event.inputs.release-tag-number }}
          user-email: ${{ secrets.USER_EMAIL }}
          user-name: ${{ secrets.USER_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
